### ISSUE TITLE
Activate Travis CI

### ISSUE THREAD

**Issue by richelbilderbeek** [Lumphie/CourseCPP#2]
Cannot do this, only @Lumphie has this power :-)

**Comment by Lumphie** [comment]
You'll have to teach me how then!

**Comment by richelbilderbeek** [comment]
- Go to `travis-ci.org`
- Click `Sync account`
- Set the slider of `CourseCPP` to green

**Comment by richelbilderbeek** [comment]
... and then push something to GitHub to start the first Travis build. I can do this step :sunglasses:

**Comment by Lumphie** [comment]
I synced it now but it cannot find .travis.yml

**Comment by richelbilderbeek** [comment]
I'll fix that now for ya

**Comment by richelbilderbeek** [comment]
OCLint suggestions are already visible in the Travis CI log...

**Comment by richelbilderbeek** [comment]
Done! 

I have modified some code, by adding a proper constructor (the `reset` member function is a rather obsolete `C` style).

To view code coverage, you may have to click the codecov badge at `README.md` and activate a Codecov account (free, can use your GitHub account). Or perhaps the OCLint suggestions may have to be fixed :-)

Good luck!
